# Reading & Writing Files in Pandas

## CSV Files

### Read CSV
```python
df = pd.read_csv("data.csv")
```

Options:
```python
pd.read_csv("data.csv", usecols=["Name", "Age"], nrows=10)
```

### Write CSV
```python
df.to_csv("output.csv", index=False)
```

---

## Excel Files

### Read Excel
```python
df = pd.read_excel("data.xlsx")
```

Options:
```python
pd.read_excel("data.xlsx", sheet_name="Sales")
```

### Write Excel
```python
df.to_excel("output.xlsx", index=False)
```

Multiple sheets:
```python
with pd.ExcelWriter("report.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Summary", index=False)
    df2.to_excel(writer, sheet_name="Details", index=False)
```

---

## JSON Files

### Read JSON
```python
df = pd.read_json("data.json")
```


## Summary

- `read_*` and `to_*` methods for CSV, Excel, JSON
- Use `sheet_name` for Excel

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("data_1.csv")

In [7]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
df = df[df['IMDb']>6.0]

In [9]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [10]:
df.to_csv("data_updated.csv", index=False)

In [12]:
df = pd.read_json("my.json")

In [13]:
df

,collectionName,owner,created,books
0,Personal Reading List,mussab,2025-11-12T00:00:00Z,"{'id': 1, 'title': 'Learning Pythonic Patterns..."
1,Personal Reading List,mussab,2025-11-12T00:00:00Z,"{'id': 2, 'title': 'Practical Algorithms', 'au..."
2,Personal Reading List,mussab,2025-11-12T00:00:00Z,"{'id': 3, 'title': 'Web Development Essentials..."

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   collectionName  3 non-null      object
 1   owner           3 non-null      object
 2   created         3 non-null      object
 3   books           3 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes

In [15]:
data = [
    
    {"id": 1, "name": "Alice", "address": {"city": "Delhi", "zipcode": "110001"}},
    {"id": 2, "name": "Bob", "address": {"city": "Mumbai", "zipcode": "400001"}}
]

In [16]:
df = pd.json_normalize(data)

In [17]:
df

   id   name address.city address.zipcode
0   1  Alice        Delhi          110001
1   2    Bob       Mumbai          400001

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2 non-null      int64
 1   name             2 non-null      object
 2   address.city     2 non-null      object
 3   address.zipcode  2 non-null      object
dtypes: int64(1), object(3)
memory usage: 196.0+ bytes